# LagBox Config
# All times are in milliseconds
# Do not set the lagtime value to a large value, you may trigger the Spigot watchdog
# CHANGING THE VERSION VALUE WILL RESULT IN A CONFIG WIPE.
version: 102
lagtime: 1000
lagchat: true
message: "I'm the one who lagged the server, blame me!"
