name: LagBox
main: net.brutuscat.LagBox.LagBox
version: 1.0
load: startup
author: brutuscat2
website: https://brutuscat.net
description: "Lags your server when you say lag"
commands:
  lbreload:
    description: Reload plugin configuration
    usage: /reload
    permission: lagbox.reload
    permission-message: You don't have permissions for this command.
